Add SwiftPM support
alexandreos/UILabel-Copyable pull request #3
Opened 2021-03-05 21:53 UTC by maxwellainatchi

Adds support for Swift Package Manager

2021-03-05 23:44 UTC, alexandreos requested changes
Hi @maxwellainatchi, thanks for your PR.
Could you please update the package/library name?

2021-03-05 23:44 UTC, alexandreos commented on Package.swift
> +    name: "UILabel-Copyable",
It would be better to keep the package name the same as the Pod/Library: `UILabel+Copyable`
```suggestion
    name: "UILabel+Copyable",
```

2021-03-05 23:44 UTC, alexandreos commented on Package.swift
> +            name: "UILabel-Copyable",
```suggestion
            name: "UILabel+Copyable",
```

2021-03-07 15:05 UTC, maxwellainatchi commented
@alexandreos, from my testing, it looks like this change is invalid. On this branch, my test project now throws an error when trying to include the package.
<img width="249" alt="image" src="https://user-images.githubusercontent.com/4398327/110243861-3802e580-7f2a-11eb-9d7d-eafec8a4a8d2.png">

I'm actually unable to even open the project now, which is concerning and likely a bug in SwiftPM

2021-03-07 15:48 UTC, maxwellainatchi commented
hm actually, after diving into it a bit, seems it's only an issue if you already had the library as a SwiftPM dependency before (so only me). The issue with XCode not opening can be fixed by deleting the `[project name].xcworkspace/xcuserdata/[your username].xcuserdatad/UserInterfaceState.xcuserstate` file

2021-03-15 14:37 UTC, maxwellainatchi commented
Just wanted to be clear, this PR is safe to merge (no issues with the name), and the requested changes were addressed!

2021-03-15 17:58 UTC, alexandreos approved these changes
Looks good to me 👍 
Thanks @maxwellainatchi

2021-03-15 17:59 UTC, merged